spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: 160728
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "placeHolder"
  expiration: 3600000  # 1 hour
server:
  port: 8081
